IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'mdb')
    BEGIN
        EXEC('CREATE SCHEMA mdb');
    END;
GO
IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'musicdb')
    BEGIN
        EXEC('CREATE DATABASE musicdb');
    END;
GO
use musicdb;
CREATE LOGIN prospring5 WITH PASSWORD = 'KkSLMSnLSO1KJj3JL'
CREATE USER  prospring5 FOR LOGIN prospring5;

CREATE TABLE mdb.SINGER (
                        ID INT NOT NULL IDENTITY(1,1),
                        FIRST_NAME VARCHAR(60) NOT NULL,
                        LAST_NAME VARCHAR(40) NOT NULL,
                        BIRTH_DATE DATE,
                        VERSION INT NOT NULL DEFAULT 0,
                        CONSTRAINT UQ_SINGER1 UNIQUE (FIRST_NAME, LAST_NAME),
                        PRIMARY KEY (ID)
);

CREATE TABLE mdb.ALBUM (
                       ID INT NOT NULL IDENTITY(1,1),
                       SINGER_ID INT NOT NULL,
                       TITLE VARCHAR(100) NOT NULL,
                       RELEASE_DATE DATE,
                       VERSION INT NOT NULL DEFAULT 0,
                       CONSTRAINT UQ_SINGER_ALBUM UNIQUE (SINGER_ID, TITLE),
                       CONSTRAINT FK_ALBUM_SINGER FOREIGN KEY (SINGER_ID) REFERENCES mdb.SINGER (ID),
                       PRIMARY KEY (ID)
);

CREATE TABLE mdb.INSTRUMENT (
    INSTRUMENT_ID VARCHAR(20) NOT NULL,
    PRIMARY KEY (INSTRUMENT_ID)
);

CREATE TABLE mdb.SINGER_INSTRUMENT (
    SINGER_ID INT NOT NULL,
    INSTRUMENT_ID VARCHAR(20) NOT NULL,
    CONSTRAINT FK_SINGER_INSTRUMENT1 FOREIGN KEY (SINGER_ID) REFERENCES mdb.SINGER (ID) ON DELETE CASCADE,
    CONSTRAINT FK_SINGER_INSTRUMENT2 FOREIGN KEY (INSTRUMENT_ID) REFERENCES mdb.INSTRUMENT (INSTRUMENT_ID)
);

ALTER USER prospring5 WITH DEFAULT_SCHEMA = mdb;

