CREATE LOGIN prospring5 WITH PASSWORD = 'KkSLMSnLSO1KJj3JL'
CREATE USER  prospring5 FOR LOGIN prospring5;

CREATE TABLE SINGER (
    ID INT NOT NULL IDENTITY(1,1),
    FIRST_NAME VARCHAR(60) NOT NULL,
    LAST_NAME VARCHAR(40) NOT NULL,
    BIRTH_DATE DATE,
    CONSTRAINT UQ_SINGER1 UNIQUE (FIRST_NAME, LAST_NAME),
    PRIMARY KEY (ID)
);

CREATE TABLE ALBUM (
    ID INT NOT NULL IDENTITY(1,1),
    SINGER_ID INT NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    RELEASE_DATE DATE,
    CONSTRAINT UQ_SINGER_ALBUM UNIQUE (SINGER_ID, TITLE),
    CONSTRAINT FK_ALBUM FOREIGN KEY (SINGER_ID) REFERENCES SINGER (ID),
    PRIMARY KEY (ID)
);